name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config --global user.email "arnespoprzenovic@gmail.com"
          git config --global user.name "apoprzenovic"

      - name: Deploying the static website to gh-pages
        run: npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}